apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devrepo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devrepo
  template:
    metadata:
      labels:
        app: devrepo
    spec:
      containers:
      - name: devrepo
        image: asia-south1-docker.pkg.dev/poc101-500018/gcppoc/devrepo:0a774d0119de61a9b21fab528964421a202c2344
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: devrepo-service
  namespace: dev
spec:
  selector:
    app: devrepo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
